version: "3.7"
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: webbythien
      MYSQL_DATABASE: PRM
    ports:
      - 3306:3306
    # volumes:
    #   - ./sql/gptstore.sql:/docker-entrypoint-initdb.d/init-script.sql
    # networks:
      # - gptstore-network

  # phpmyadmin8-container:
  #   container_name: phpmyadmin8-container
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   depends_on:
  #     - mysql8-container
  #   ports:
  #     - "8100:80" #port mapping
  #   environment:
  #     PMA_HOST: mysql8-container #phpMyAdmin Host
  #   networks:
