FROM node:12.22.0 AS builder
RUN mkdir /app
WORKDIR /app
COPY . .
RUN npm install && node genNginx.js

FROM nginx:1.19.2
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /app/log/
RUN touch /app/log/error.log
EXPOSE 443
